language: node_js
node_js:
    - "node"
    - "8"
script:
    - npm run optimize
    - npm run build
    - npm test
cache:
    directories:
        - "node_modules"
env:
    CODECLIMATE_REPO_TOKEN: f0edba526a656286552680b23eb0a28529d54a05dfb047e0fc1d0068314e3a3d
