language: node_js
node_js:
    - "node"
    - "8"
before_script:
    - npm install -g svgo
script:
    - ./build.sh
cache:
    directories:
        - "node_modules"
env:
    CODECLIMATE_REPO_TOKEN: f0edba526a656286552680b23eb0a28529d54a05dfb047e0fc1d0068314e3a3d
